### PR TITLE
Replace imagehlp with pe-parse

### LINKED ISSUE #26: doesn't work with 32bit PE files

### LINKED ISSUE #27: Replace ImageHlp with our own pe-parse
ImageHlp can't (correctly) parse 32-bit binaries when built into a 64-bit build of winchecksec and vice versa. It's also a PITA to use and needs to be wrapped to conform to C++ idioms.

We should really just use our own [pe-parse](https://github.com/trailofbits/pe-parse) instead. PRs appreciated.

### PR DESCRIPTION
**Pull request by inventednight**
Closes #27 
Closes #26

### CODE REVIEW

File: Checksec.cpp [hunk 1]
```diff
@@ -16,246 +19,261 @@ using json = nlohmann::json;
...
 
-    // can't make copies of LoadedImage
-    LoadedImage(const LoadedImage&) = delete;
-    LoadedImage& operator=(const LoadedImage&) = delete;
+  // can't make copies of LoadedImage
+  LoadedImage(const LoadedImage &) = delete;
+  LoadedImage &operator=(const LoadedImage &) = delete;
 
-private:
+  peparse::parsed_pe *get() { return pe_; }
```
Comment (woodruffw) [inline Checksec.cpp]: Hmm, let's get rid of `get()` entirely and add an `operator&` overload, so that we can do `&loadedImage` directly below.

Something like this should work:

```c++
  peparse::parsed_pe *operator&() { return pe_; }
```

File: Checksec.cpp [hunk 2]
```diff
@@ -16,246 +19,261 @@ using json = nlohmann::json;
...
+      cerr << "Warn: short image data directory vector (no CLR info?)"
+           << "\n";
+      return;
     }
-
-    clrConfig_ = imageOptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR];
+    clrConfig_ = optionalHeader->DataDirectory[peparse::DIR_COM_DESCRIPTOR];
 
     // Warn and return early if the image data directory vector
     // is too short to contain a reference to the IMAGE_LOAD_CONFIG_DIRECTORY.
```
Comment (woodruffw) [inline Checksec.cpp]: Nit: `IMAGE_LOAD_CONFIG_DIRECTORY` is now `DIR_LOAD_CONFIG` (and below)

File: Checksec.cpp [hunk 3]
```diff
@@ -16,246 +19,261 @@ using json = nlohmann::json;
...
+    peparse::optional_header_32 *optionalHeader = &(nt.OptionalHeader);
+    dllCharacteristics_ = optionalHeader->DllCharacteristics;
+    if (optionalHeader->NumberOfRvaAndSizes < peparse::DIR_COM_DESCRIPTOR + 1) {
+      cerr << "Warn: short image data directory vector (no CLR info?)"
+           << "\n";
+      return;
+    }
+    clrConfig_ = optionalHeader->DataDirectory[peparse::DIR_COM_DESCRIPTOR];
+    // Warn and return early if the image data directory vector
+    // is too short to contain a reference to the IMAGE_LOAD_CONFIG_DIRECTORY.
```
Comment (woodruffw) [inline Checksec.cpp]: Same as above.

**Comment by woodruffw** [comment]
One last nit: Let's update the README to reflect the fact that builds now depend on a submodule, and let's link to pe-parse as our one dependency.

File: README.md [hunk 4]
```diff
@@ -19,11 +19,13 @@ The following security features are currently detected:
 
 ## Building
 
-`winchecksec` has no dependencies other than Windows itself, and should build
+`winchecksec` depends on pe-parse, and should build
```
Comment (woodruffw) [inline README.md]: Nit: Add a link to pe-parse
