### PR TITLE
Correct logic in #1039.

### LINKED ISSUE #1038: Incorrect Offsets in loadConfigSize_ Checks?
It appears that the fast out checks for `loadConfigSize_` thresholds are hardcoded for x64 and thus result in incorrect reports for x86 binaries.

I think they’re based on Microsoft’s [Load Configuration Layout table](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#load-configuration-layout) which lists sizes for both 32 bit and 64 bit binaries, and that perhaps only the right hand side of the Offset column was used by mistake.

For example  `isSafeSEH`’s [`loadConfigSize_` check](https://github.com/trailofbits/winchecksec/blob/ccd02845b85b089b8ca287084bae03aa89cb7841/checksec.cpp#L222-L227) specifies `112`, but this is correct only for x64 binaries, which of course don’t use SafeSEH at all. The correct value to check against would appear to be `72`, and thus the current checks may result in false negatives.

Provided I haven’t completely misunderstood this then there’d be two options:
1. Set all the checks to the x86 offsets as they’re the lower of the two, or
2. Support both sets of offsets so that the fast out can still be used in 100% of cases.

### PR DESCRIPTION
**Pull request by karanlyons**
(That’ll teach me to make midnight PRs.)

The previous PR I filed unfortunately got the logic wrong, rendering the 32 bit checks a no-op. It also used checks for `IMAGE_FILE_MACHINE_I386`, but while I’m cleaning up after myself I think `IMAGE_FILE_32BIT_MACHINE` should be more accurate as to the intent with these checks.

This should *actually* fix #1038, while remaining performant.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks. That'll teach me to review PRs over the weekend as well 😉.

Looks like there are some conflicts with `master`. Would you mind resolving them?

**Review by woodruffw — APPROVED** [review]

File: checksec.cpp [hunk 1]
```diff
@@ -199,8 +199,8 @@ const MitigationReport Checksec::isRFG() const {
     // NOTE(ww): a load config under 92/148 bytes implies the absence of the
     // GuardFlags field. See:
     // https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#load-configuration-layout
-    if ((targetMachine_ == peparse::IMAGE_FILE_MACHINE_I386 && loadConfigSize_ < 92) ||
-        loadConfigSize_ < 148) {
+    if (loadConfigSize_ < 148 &&
+        !(imageCharacteristics_ == peparse::IMAGE_FILE_32BIT_MACHINE && loadConfigSize_ >= 92)) {
```
Comment (woodruffw) [inline checksec.cpp]: I _think_ this check is slightly wrong: `imageCharacteristics_` is a bitfield, with `0x0100` indicating `IMAGE_FILE_32_BIT_MACHINE`.  So, I think this actually needs to be:

```c++
((imageCharacteristics_ & peparse::IMAGE_FILE_32BIT_MACHINE) && loadConfigSize_ >= 92)
```

Otherwise, this'll still be a consistent no-op for the majority of binaries.

Comment (woodruffw) [reply checksec.cpp]: Whoops, beat me to it!

Comment (karanlyons) [reply checksec.cpp]: Please squash my sins 😅

**Comment by woodruffw** [comment]
Thanks again. Will cut as 3.0.2.
